let programs = [
    {
        id: 1,
        title: "Beginner Piano",
        description: "Learn the basics of piano playing.",
        price: 2000,
        image: "/Media/Programs/piano.jpg",
        availableInventory: 5,
        rating: 3,
        category: "Music",
        location: "Music Hall A"
    },
    {
        id: 2,
        title: "Advanced Math Tutoring",
        description: "Master advanced math concepts.",
        price: 2500,
        image: "/Media/Programs/math.jpg",
        availableInventory: 5,
        rating: 4,
        category: "Education",
        location: "Room 101"
    },
    {
        id: 3,
        title: "Soccer Skills for Kids",
        description: "Enhance soccer skills with top coaches.",
        price: 1500,
        image: "/Media/Programs/soccer.jpg",
        availableInventory: 5,
        rating: 5,
        category: "Sports",
        location: "Soccer Field 1"
    },
    {
        id: 4,
        title: "French Language Course",
        description: "Learn French from native speakers.",
        price: 1800,
        image: "/Media/Programs/french.jpg",
        availableInventory: 5,
        rating: 3,
        category: "Education",
        location: "Room 202"
    },
    {
        id: 5,
        title: "Guitar Lessons for Beginners",
        description: "Learn to play the guitar with ease.",
        price: 2200,
        image: "/Media/Programs/guitar.jpg",
        availableInventory: 5,
        rating: 5,
        category: "Music",
        location: "Music Hall B"
    },
    {
        id: 6,
        title: "Science Experiments for Kids",
        description: "Conduct fun and educational science experiments.",
        price: 1000,
        image: "/Media/Programs/science.jpg",
        availableInventory: 5,
        rating: 4,
        category: "Education",
        location: "Lab 3"
    },
    {
        id: 7,
        title: "Yoga for Beginners",
        description: "Improve flexibility and balance with yoga.",
        price: 1200,
        image: "/Media/Programs/yoga.jpg",
        availableInventory: 5,
        rating: 2,
        category: "Sports",
        location: "Yoga Studio"
    },
    {
        id: 8,
        title: "Art Classes for Adults",
        description: "Explore your creativity with art classes.",
        price: 2500,
        image: "/Media/Programs/art.jpg",
        availableInventory: 5,
        rating: 5,
        category: "Art",
        location: "Art Room 4"
    },
    {
        id: 9,
        title: "Chess Club for Kids",
        description: "Improve strategic thinking with chess.",
        price: 800,
        image: "/Media/Programs/chess.jpg",
        availableInventory: 5,
        rating: 3,
        category: "Education",
        location: "Room 303"
    },
    {
        id: 10,
        title: "Dance Lessons for Teens",
        description: "Learn popular dance styles with experienced instructors.",
        price: 2000,
        image: "/Media/Programs/dance.jpg",
        availableInventory: 5,
        rating: 4,
        category: "Sports",
        location: "Dance Hall A"
    },
    {
        id: 11,
        title: "Cooking Classes for Beginners",
        description: "Learn to cook with experienced chefs.",
        price: 2200,
        image: "/Media/Programs/cooking.jpg",
        availableInventory: 5,
        rating: 5,
        category: "Education",
        location: "Kitchen 1"
    },
    {
        id: 12,
        title: "Photography Workshop",
        description: "Improve your photography skills with experts.",
        price: 2500,
        image: "/Media/Programs/photography.jpg",
        availableInventory: 5,
        rating: 4,
        category: "Art",
        location: "Photo Lab"
    },
    {
        id: 13,
        title: "Karate Classes for Kids",
        description: "Learn karate techniques and self-defense.",
        price: 1800,
        image: "/Media/Programs/karate.jpg",
        availableInventory: 5,
        rating: 2,
        category: "Sports",
        location: "Martial Arts Room"
    },
    {
        id: 14,
        title: "Vocal Lessons for Adults",
        description: "Improve your singing voice with experienced instructors.",
        price: 2000,
        image: "/Media/Programs/vocals.jpg",
        availableInventory: 5,
        rating: 5,
        category: "Music",
        location: "Music Hall C"
    },
    {
        id: 15,
        title: "Basketball Training for Teens",
        description: "Improve your basketball skills with top coaches.",
        price: 1500,
        image: "/Media/Programs/basketball.jpg",
        availableInventory: 5,
        rating: 4,
        category: "Sports",
        location: "Basketball Court"
    },
    {
        id: 16,
        title: "Coding for Kids",
        description: "Learn the basics of coding in a fun and interactive way.",
        price: 1200,
        image: "/Media/Programs/coding.jpg",
        availableInventory: 5,
        rating: 3,
        category: "Education",
        location: "Computer Lab 2"
    },
    {
        id: 17,
        title: "Robotics Workshop",
        description: "Build and program your own robots.",
        price: 2500,
        image: "/Media/Programs/robotics.jpg",
        availableInventory: 5,
        rating: 4,
        category: "Education",
        location: "Lab 5"
    },
    {
        id: 18,
        title: "Guitar Lessons for Adults",
        description: "Learn to play the guitar with ease.",
        price: 2200,
        image: "/Media/Programs/guitar.jpg",
        availableInventory: 5,
        rating: 5,
        category: "Music",
        location: "Music Hall D"
    },
    {
        id: 19,
        title: "Painting Classes for Teens",
        description: "Explore your artistic talents with painting classes.",
        price: 1800,
        image: "/Media/Programs/painting.jpg",
        availableInventory: 5,
        rating: 4,
        category: "Art",
        location: "Art Room 7"
    },
    {
        id: 20,
        title: "Swimming Lessons for Kids",
        description: "Learn to swim safely and confidently.",
        price: 1000,
        image: "/Media/Programs/swimming.jpg",
        availableInventory: 5,
        rating: 3,
        category: "Sports",
        location: "Swimming Pool A"
    }
];
